### ISSUE TITLE
Problem for proceeding `yarn install`

### ISSUE THREAD

**Issue by Jeong-jj** [mincho-js/mincho#51]
### Packages with the problem

Configs (Vite, Lint, Typescript ..etc)

### Describe the bug

When I proceed `yarn install` script, I get a following error

```bash
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 27 packages were added to the project, and 30 were removed (+ 1.74 MiB).
➤ YN0000: └ Completed in 9s 768ms
➤ YN0000: ┌ Link step
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: EXDEV: cross-device link not permitted, link 'C:\Users\Mine\AppData\Local\Yarn\Berry\index\80\80674912e3033be358331910ba27d5812369c2fc.dat' -> 'D:\Mine\mincho-project\mincho.js\node_modules\.store\boxen-npm-8.0.0-0f4620e170\package\license'] {
  errno: -4037,
  code: 'EXDEV',
  syscall: 'link',
  path: 'C:\\Users\\Mine\\AppData\\Local\\Yarn\\Berry\\index\\80\\80674912e3033be358331910ba27d5812369c2fc.dat',
  dest: 'D:\\Mine\\mincho-project\\mincho.js\\node_modules\\.store\\boxen-npm-8.0.0-0f4620e170\\package\\license'
}

Node.js v20.15.1
```

It could be happen bacause I locate project folder in D drive

### Steps To Reproduce

So, I add some options in `yarnrc.yml`

```yml
cacheFolder: ./.yarn/cache

checksumBehavior: reset

compressionLevel: mixed

enableGlobalCache: true

globalFolder: ./.yarn/cache

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
```
